apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
data:
  mongodb-username: bXVjaHRvZG9fdXNlcg==  # muchtodo_user
  mongodb-password: bXVjaHRvZG9fcGFzcw==  # muchtodo_pass
