apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
  namespace: muchtodo
data:
  mongodb-init.js: |
    db.createUser({
      user: "muchtodo_user",
      pwd: "userpassword123",
      roles: [
        { role: "readWrite", db: "muchtodo" }
      ]
    });