apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: muchtodo
data:
  PORT: "8080"
  LOG_LEVEL: "info"
  MONGODB_URI: mongodb://muchtodo_user:muchtodo_pass@mongodb.muchtodo.svc.cluster.local:27017/muchtodo?authSource=admin
