apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: muchtodo
  labels:
    app: backend
data:
  DB_HOST: mongodb-service.muchtodo.svc.cluster.local
  DB_PORT: "27017"
  DB_NAME: muchtodo
  DB_USERNAME: muctodo_user
  SERVER_PORT: "8080"