apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:example@mongodb:27017/much_todo_db?authSource=admin"
  JWT_SECRET_KEY: "dev-secret-key-change-me"